---
title: "DNA Query"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(stringr)
library(tidyr)
library(plyr)
library(dplyr)
library(lubridate)
library(data.table)
library(gtsummary)

#This code runs a DNA sample query for all PROMOTE participants

#Finds list of participants with a DNA sample and their demographics

#CHANGE FILE PATHS

```

#Import Files
```{r}
#setwd("your_working_directory")

database <- read.csv("database.csv") #Export of the whole database project
database <- database %>% filter(!str_detect(id_participant, "_x"))

#Have DNA sequenced (regeneron)
sequenced <- read.csv("genomic_prts_final.csv") #The final manifest of dna samples after quality controls were resolved- should have 1052 participants
sequenced$dna_sequenced <- 1
sequenced <- sequenced[,c("id_participant", "dna_sequenced")]
sequenced <- unique(sequenced)
names(sequenced)[1] <- 'id_participant'

```


#DNA samples
```{r}
dna <- database[,c("id_participant", "blood1_date", "blood1_dna", "blood1_dnanum", "subtype_blood", "blood1_dmt_detail")]
dna <- dna %>% filter(blood1_dnanum>0)
dna$blood1_date <- as.Date(dna$blood1_date)

sum(table(unique(dna$id_participant))) #1303 unique participants, 1346 samples

dna <- merge(dna, sequenced, by = 'id_participant', all.x = TRUE)

```

#Demographics
```{r}
demogs <- database[,c("id_participant", "dob", "subject_sex", "race", "ethnicity", "date_firstsx", "date_msdx", "subject_group", "related_name")]
demogs <- demogs %>% filter(subject_sex>0)
dna2 <- merge(demogs, dna, by = 'id_participant', all.y = TRUE)

#Calculate age and disease duration
dna2$blood1_date <- as.Date(dna2$blood1_date)
dna2$dob <- as.Date(dna2$dob)
dna2$blood1_date <- as.Date(dna2$blood1_date)
dna2$date_firstsx <- as.Date(dna2$date_firstsx)
dna2$age_collection <- as.numeric(difftime(dna2$blood1_date, dna2$dob, units="weeks")/52.25)
dna2$disease_duration <- as.numeric(difftime(dna2$blood1_date, dna2$date_firstsx, units="weeks")/52.25)

#relabel fields
dna2$subject_sex <- factor(dna2$subject_sex, levels = c(1,2), labels = c("Male", "Female"))
dna2$subject_group <- factor(dna2$subject_group, levels = c(1,2,3,99), labels = c("MS", "Other NID", "Controls", "Unknown"))
dna2$race <- factor(dna2$race, levels = c(1,2,3,4,5,99), labels = c("Black", "American Indian or Alaska Native", "Asian", "Caucasian", "Multi-racial", "Not Sure"))
dna2$ethnicity <- factor(dna2$ethnicity, levels = c(1,2,99), labels = c("Hispanic or Latino", "Non-Hispanic or Latino", "Not Sure"))
dna2$subtype_blood <- factor(dna2$subtype_blood, levels = c(1,2,3,4,5,6,99), labels = c("CIS", "RIS", "RRMS", "SPMS", "PPMS", "NMO", "Does not have MS"))
dna2$blood1_dmt_detail <- factor(dna2$blood1_dmt_detail, levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,99), labels=c("Teriflunomide (Aubagio)", "Interferon Beta-1a (Avonex)", "Interferon Beta-1b (Betaseron)", "Glatiramer acetate (Copaxone/ Glatopa)", "Interferon Beta-1b (Extavia)", "Fingolimod (Gilenya)", "Mitoxantrone (Novantrone)", "Interferon Beta-1a (Rebif)", "Dimethyl fumarate/BG12 (Tecfidera)", "Natalizumab (Tysabri)", "Other", "Alemtuzumab/ Campath (Lemtrada)",  "Ocrelizumab (Ocrevus)", "Pegylated interferon Beta-1a (Plegridy)", "Daclizumab (Zinbryta)", "Rituximab (Rituxan)", "Cladribine (Mavenclad)", "Siponimod (Mayzent)", "Diroximel Fumarate (Vumerity)", "Ozanimod (Zeposia)", "Ofatumumab (Kesimpta)", "Eculizumab (Soliris)", "Inebilizumab-cdon (Uplizna)", "Satralizumab-mwge (Enspryng)", "Ponesimod (Ponvory)", "Monomethyl Fumarate (Bafiertam)", "None"))
dna2$dna_sequenced <- replace_na(dna2$dna_sequenced, 2)
dna2$dna_sequenced <- factor(dna2$dna_sequenced, levels = c(1,2), labels = c("Yes", "No"))


dna2$dmt_class <- factor(dna2$blood1_dmt_detail, levels = c("Teriflunomide (Aubagio)", "Interferon Beta-1a (Avonex)", "Interferon Beta-1b (Betaseron)", "Glatiramer acetate (Copaxone/ Glatopa)", "Interferon Beta-1b (Extavia)", "Fingolimod (Gilenya)", "Mitoxantrone (Novantrone)", "Interferon Beta-1a (Rebif)", "Dimethyl fumarate/BG12 (Tecfidera)", "Natalizumab (Tysabri)", "Other", "Alemtuzumab/ Campath (Lemtrada)",  "Ocrelizumab (Ocrevus)", "Pegylated interferon Beta-1a (Plegridy)", "Daclizumab (Zinbryta)", "Rituximab (Rituxan)", "Cladribine (Mavenclad)", "Siponimod (Mayzent)", "Diroximel Fumarate (Vumerity)", "Ozanimod (Zeposia)", "Ofatumumab (Kesimpta)", "Eculizumab (Soliris)", "Inebilizumab-cdon (Uplizna)", "Satralizumab-mwge (Enspryng)", "Ponesimod (Ponvory)", "Monomethyl Fumarate (Bafiertam)", "None"),
                         labels = c("pyrimidine blocker", "interferon-beta", "interferon-beta", "glatiramer acetate", "interferon-beta", "S1P R modulator", "cell proliferation blocker", "interferon-beta", "fumarate", "alpha4-integrin blocker", "Other", "chemotherapy",  "B cell depletion", "interferon-beta", "IL2R blocker", "B cell depletion", "purine analog", "S1P R modulator", "fumarate", "S1P R modulator", "B cell depletion", "C5 blocker", "B cell depletion", "IL6R blocker", "S1P R modulator", "fumarate", "None"))

write.csv(dna2, "dna.csv")

dna2 <- dna2[,c("id_participant", "dob", "subject_group", "related_name", "age_collection", "subject_sex", "race", "ethnicity", "blood1_date", "subtype_blood", "dna_sequenced", "disease_duration", "blood1_dmt_detail", "dmt_class")]

#generate table
select(dna2, c(age_collection, subject_sex, race, ethnicity, subtype_blood, dna_sequenced, disease_duration, blood1_dmt_detail, dmt_class)) %>%
    tbl_summary(statistic = list(c(age_collection, disease_duration) ~ "{mean} ({sd})"),
                digits = list(c(age_collection, disease_duration) ~ 2),
                missing_text = "Missing",
                label = list(age_collection ~ "Age (years, mean ± SD)", disease_duration ~ "Disease Duration (years, mean ± SD)", subject_sex ~ "Sex (n, % of cohort)", race ~ "Race (n, % of cohort)", ethnicity ~ "Ethnicity (n, % of cohort)", subtype_blood ~ "Disease Subtype (n, % of cohort)", dna_sequenced ~ "Samples Sequenced (n, % of Cohort)", blood1_dmt_detail ~ "DMT (n, % of cohort)", dmt_class ~ "DMT Class (n, % of  cohort)")
  ) %>%
  bold_labels()


```





