---
title: "Plasma Query"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(stringr)
library(tidyr)
library(plyr)
library(dplyr)
library(lubridate)
library(data.table)
library(gtsummary)

#This code runs a plasma sample query for all PROMOTE participants

#Finds list of participants with a plasma sample and their demographics

#CHANGE FILE PATHS
  
```

#Import Files
```{r}
setwd("") #Set working directory here

database <- read.csv("database.csv") #Export of the whole PROMOTE database project
database <- database %>% filter(!str_detect(id_participant, "_x"))


```

#PBMC Samples
```{r}
plasma <- database[,c("id_participant", "blood1_date", "blood1_plasma", "subtype_blood", "blood1_dmt_detail")]
plasma <- plasma %>% filter(blood1_plasma>0)
sum(table(unique(plasma$id_participant))) #900 unique participants, 1354 samples

```

#Demographics
```{r}
demogs <- database[,c("id_participant", "dob", "subject_sex", "race", "ethnicity", "dx_group_main", "date_firstsx", "date_msdx")]
demogs <- demogs %>% filter(subject_sex>0)
plasma2 <- merge(demogs, plasma, by = 'id_participant', all.y = TRUE)

#Calculate age and disease duration
plasma2$blood1_date <- as.Date(plasma2$blood1_date)
plasma2$dob <- as.Date(plasma2$dob)
plasma2$blood1_date <- as.Date(plasma2$blood1_date)
plasma2$date_firstsx <- as.Date(plasma2$date_firstsx)
plasma2$age_collection <- as.numeric(difftime(plasma2$blood1_date, plasma2$dob, units="weeks")/52.25)
plasma2$disease_duration <- as.numeric(difftime(plasma2$blood1_date, plasma2$date_firstsx, units="weeks")/52.25)

#relabel fields
plasma2$subject_sex <- factor(plasma2$subject_sex, levels = c(1,2), labels = c("Male", "Female"))
plasma2$race <- factor(plasma2$race, levels = c(1,2,3,4,5,99), labels = c("Black", "American Indian or Alaska Native", "Asian", "Caucasian", "Multi-racial", "Not Sure"))
plasma2$ethnicity <- factor(plasma2$ethnicity, levels = c(1,2,99), labels = c("Hispanic or Latino", "Non-Hispanic or Latino", "Not Sure"))
plasma2$dx_group_main <- factor(plasma2$dx_group_main, levels = c(1,2,3,4,5,6), labels = c("Healthy Control", "MS", "MOGAD", "Myelitis", "NMOSD", "Unknown"))
plasma2 <- plasma2 %>%
  mutate(subtype_blood = case_when(
    subtype_blood %in% c(1, 2, 3, 4, 5) ~ factor(subtype_blood, levels = c(1, 2, 3, 4, 5), labels = c("CIS", "RIS", "RRMS", "SPMS", "PPMS")),
    TRUE ~ "Not MS"  # Any other values
  ))
plasma2$subtype_blood <- factor(plasma2$subtype_blood, levels = c("CIS", "RIS", "RRMS", "SPMS", "PPMS", "Not MS"))
#plasma2$subtype_blood <- factor(plasma2$subtype_blood, levels = c(1,2,3,4,5), labels = c("CIS", "RIS", "RRMS", "SPMS", "PPMS"))
plasma2$blood1_dmt_detail <- factor(plasma2$blood1_dmt_detail, levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,99), labels = c("Aubagio", "Avonex", "Betaseron", "Copaxone", "Extavia", "Gilenya", "Novantrone", "Rebif", "Tecfidera", "Tysabri", "Other", "Lemtrada",  "Ocrevus", "Plegridy", "Zinbryta", "Rituxan", "Mavenclad", "Mayzent", "Vumerity", "Zeposia", "Kesimpta", "Soliris", "Uplizna", "Enspryng", "Ponvory", "Bafiertam", "None"))

write.csv(plasma2, "plasma.csv")

plasma2 <- plasma2[,c("id_participant", "dob", "age_collection", "subject_sex", "race", "ethnicity", "dx_group_main", "blood1_date", "subtype_blood", "disease_duration", "blood1_dmt_detail")]

#generate table
select(plasma2, c(age_collection, subject_sex, race, ethnicity, subtype_blood, disease_duration, blood1_dmt_detail)) %>%
    tbl_summary(statistic = list(c(age_collection, disease_duration) ~ "{mean} ({sd})"),
                digits = list(c(age_collection, disease_duration) ~ 2),
                label = list(age_collection ~ "Age (years, mean ± SD)", disease_duration ~ "Disease Duration (years, mean ± SD)", subject_sex ~ "Sex (n, % of cohort)", race ~ "Race (n, % of cohort)", ethnicity ~ "Ethnicity (n, % of cohort)", subtype_blood ~ "Disease Subtype (n, % of cohort)", blood1_dmt_detail ~ "DMT (n, % of cohort)")
  ) %>%
  modify_footnote(update = everything() ~ NA)


```


