---
title: "FAMS Scoring"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyr)

#Scores FAMS measures and totals all subgroups for all PROMOTE participants
  #58 total questions (columns 2-59)
  #7 subgroups
  #score range: 0-176, higher=better quality of life

#Files used: PROMOTE Longitudinal, Legacy, Missing IDs

#CHANGE FILE PATHS

```

#Input files
```{r}
longitudinal1 <- read.csv("long1.csv") #PROMOTE longitudinal project 1
longitudinal2 <- read.csv("long2.csv") #PROMOTE longitudinal project 2
longitudinal <- rbind(longitudinal1, longitudinal2)
longitudinal <- longitudinal %>% filter(!str_detect(id_participant_l, "_x"))

legacy <- read.csv("PQ_SRO_Legacy.csv") #Export of the whole PQ/SRO Legacy project
missingID <- read.csv("MissingIdentifiers.csv") #Missing ID reference file
legacy <- (merge(missingID, legacy, by = 'record_id',  all.y = TRUE))
paste_noNA <- function(x,sep=", ") {
gsub(", " ,sep, toString(x[!is.na(x) & x!="" & x!="NA"] ) ) }
sep=", "
legacy$id_participant<- apply( legacy[ , c(2:3) ] , 1 , paste_noNA , sep=sep)

```

#Legacy SRO
##Raw subtotals
```{r}
famsLeg <- legacy[, grepl("fams",names( legacy ))]
famsLeg <- cbind(legacy$id_participant, legacy$promote_self_reported_outcomes_timestamp, famsLeg)
names(famsLeg)[1] <- 'id_participant'
names(famsLeg)[2] <- 'timestamp'

#mobility
famsLeg$fams4_mobility_gp3_familyneed <- as.numeric(as.character(factor(famsLeg$fams4_mobility_gp3_familyneed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_mobility_an6_walking <- as.numeric(as.character(factor(famsLeg$fams4_mobility_an6_walking, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_mobility_itu3_social <- as.numeric(as.character(factor(famsLeg$fams4_mobility_itu3_social, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_mobility_ms1_public <- as.numeric(as.character(factor(famsLeg$fams4_mobility_ms1_public, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_mobility_ms2_plan <- as.numeric(as.character(factor(famsLeg$fams4_mobility_ms2_plan, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$mobility <- rowSums(famsLeg[,c(3:9)], na.rm = TRUE)

#symptoms
famsLeg$fams4_symptoms_gp2_nausea <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_gp2_nausea, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_symptoms_gp4_pain <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_gp4_pain, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_symptoms_gp6_ill <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_gp6_ill, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_symptoms_hi12_weak <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_hi12_weak, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_symptoms_brm1_arthralgia <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_brm1_arthralgia, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_symptoms_ms3_headaches <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_ms3_headaches, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_symptoms_ms4_myalgia <- as.numeric(as.character(factor(famsLeg$fams4_symptoms_ms4_myalgia, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$symptoms <- rowSums(famsLeg[,c(10:16)], na.rm = TRUE)

#emotional well-being
famsLeg$fams4_emotions_ge1_sad <- as.numeric(as.character(factor(famsLeg$fams4_emotions_ge1_sad, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_emotions_ge3_hope <- as.numeric(as.character(factor(famsLeg$fams4_emotions_ge3_hope, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_emotions_ms5_trapped <- as.numeric(as.character(factor(famsLeg$fams4_emotions_ms5_trapped, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_emotions_ms6_depressed <- as.numeric(as.character(factor(famsLeg$fams4_emotions_ms6_depressed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_emotions_ms7_useless <- as.numeric(as.character(factor(famsLeg$fams4_emotions_ms7_useless, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_emotions_ms8_overwhelmed <- as.numeric(as.character(factor(famsLeg$fams4_emotions_ms8_overwhelmed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$emotional <- rowSums(famsLeg[,c(17:23)], na.rm = TRUE)


#general contentment
famsLeg$fams4_contentment_ms9_frustrated <- as.numeric(as.character(factor(famsLeg$fams4_contentment_ms9_frustrated, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$content <- rowSums(famsLeg[,c(24:30)], na.rm = TRUE)


#thinking and fatigue
famsLeg$fams4_fatigue_gp1_energy <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_gp1_energy, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_an2_tired <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_an2_tired, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_an3_starting <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_an3_starting, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_an4_finishing <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_an4_finishing, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_ms10_rest <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_ms10_rest, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_hi9_remembering <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_hi9_remembering, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_hi8_concentrating <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_hi8_concentrating, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_ms11_slow <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_ms11_slow, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_fatigue_ms12_new <- as.numeric(as.character(factor(famsLeg$fams4_fatigue_ms12_new, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$thinking <- rowSums(famsLeg[,c(31:39)], na.rm = TRUE)

#family and social well-being
famsLeg$fams4_social_ms13_understand <- as.numeric(as.character(factor(famsLeg$fams4_social_ms13_understand, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_social_ms14_leftout <- as.numeric(as.character(factor(famsLeg$fams4_social_ms14_leftout, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$family <- rowSums(famsLeg[,c(40:46)], na.rm = TRUE)


#additional concerns
famsLeg$fams4_additional_gp5_sideeffect <- as.numeric(as.character(factor(famsLeg$fams4_additional_gp5_sideeffect, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_gp7_bed <- as.numeric(as.character(factor(famsLeg$fams4_additional_gp7_bed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_ge4_nervous <- as.numeric(as.character(factor(famsLeg$fams4_additional_ge4_nervous, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_ge6_worse <- as.numeric(as.character(factor(famsLeg$fams4_additional_ge6_worse, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_ms15_heat <- as.numeric(as.character(factor(famsLeg$fams4_additional_ms15_heat, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_bl1_urinecontrol <- as.numeric(as.character(factor(famsLeg$fams4_additional_bl1_urinecontrol, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_bl2_urinefrq <- as.numeric(as.character(factor(famsLeg$fams4_additional_bl2_urinefrq, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_brm2_chills <- as.numeric(as.character(factor(famsLeg$fams4_additional_brm2_chills, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_brm3_fever <- as.numeric(as.character(factor(famsLeg$fams4_additional_brm3_fever, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsLeg$fams4_additional_ms16_muscle_spasms <- as.numeric(as.character(factor(famsLeg$fams4_additional_ms16_muscle_spasms, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))

famsLeg$additional <- rowSums(famsLeg[,c(47:60)], na.rm = TRUE)

```

##Final subscores & total
```{r}
#multiply each subgroup total by number of questions in the category
famsLeg$mobility <- famsLeg$mobility*7
famsLeg$symptoms <- famsLeg$symptoms*7
famsLeg$emotional <- famsLeg$emotional*7
famsLeg$content <- famsLeg$content*7
famsLeg$thinking <- famsLeg$thinking*9
famsLeg$family <- famsLeg$family*7
famsLeg$additional <- famsLeg$additional*14

#sum number of scores available
  #change all scores to 1
famsLeg[,c(3:60)] <- ifelse(
    ( 
        (famsLeg[,c(3:60)] >=0)
    ),
     1,  #puts this where conditions are met
     NA  #puts this where conditions are not met
)

  #sum rows to find number of questions answered per subgroup
famsLeg$mobility_count <- rowSums(famsLeg[,c(3:9)], na.rm = TRUE)
famsLeg$symptoms_count <- rowSums(famsLeg[,c(10:16)], na.rm = TRUE)
famsLeg$emotional_count <- rowSums(famsLeg[,c(17:23)], na.rm = TRUE)
famsLeg$content_count <- rowSums(famsLeg[,c(24:30)], na.rm = TRUE)
famsLeg$thinking_count <- rowSums(famsLeg[,c(31:39)], na.rm = TRUE)
famsLeg$family_count <- rowSums(famsLeg[,c(40:46)], na.rm = TRUE)
famsLeg$additional_count <- rowSums(famsLeg[,c(47:60)], na.rm = TRUE)

  #divide subgroup total by # scores available
famsLeg$mobility_final <- famsLeg$mobility/famsLeg$mobility_count
famsLeg$symptoms_final <- famsLeg$symptoms/famsLeg$symptoms_count
famsLeg$emotional_final <- famsLeg$emotional/famsLeg$emotional_count
famsLeg$content_final <- famsLeg$content/famsLeg$content_count
famsLeg$thinking_final <- famsLeg$thinking/famsLeg$thinking_count
famsLeg$family_final <- famsLeg$family/famsLeg$family_count
famsLeg$additional_final <- famsLeg$additional/famsLeg$additional_count

#total
famsLeg$fams_total <- rowSums(famsLeg[,c(75:80)], na.rm = TRUE)

#select final columns
famsLeg <- famsLeg[,c(1,2,75:82)]
famsLeg <- famsLeg %>% filter(fams_total>0)

```


#Longitudinal
```{r}
famsLong <- longitudinal[, grepl("fams",names( longitudinal ))]
famsLong <- cbind(longitudinal$id_participant, longitudinal$promote_self_reported_outcomes_timestamp, longitudinal$update_questionnaire_timestamp, famsLong)
names(famsLong)[1] <- 'id_participant'

#separate sro and update
famsSRO <- famsLong[,c(1,2,4:61)]
names(famsSRO)[2] <- 'timestamp'

famsUpd <- famsLong[,c(1,3,62:119)]
names(famsUpd)[2] <- 'timestamp'

```

##SRO
###Raw subtotals
```{r}
#mobility SRO
famsSRO$fams4_mobility_gp3_familyneed <- as.numeric(as.character(factor(famsSRO$fams4_mobility_gp3_familyneed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_mobility_an6_walking <- as.numeric(as.character(factor(famsSRO$fams4_mobility_an6_walking, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_mobility_itu3_social <- as.numeric(as.character(factor(famsSRO$fams4_mobility_itu3_social, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_mobility_ms1_public <- as.numeric(as.character(factor(famsSRO$fams4_mobility_ms1_public, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_mobility_ms2_plan <- as.numeric(as.character(factor(famsSRO$fams4_mobility_ms2_plan, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$mobility <- rowSums(famsSRO[,c(3:9)], na.rm = TRUE)

#symptoms SRO
famsSRO$fams4_symptoms_gp2_nausea <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_gp2_nausea, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_symptoms_gp4_pain <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_gp4_pain, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_symptoms_gp6_ill <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_gp6_ill, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_symptoms_hi12_weak <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_hi12_weak, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_symptoms_brm1_arthralgia <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_brm1_arthralgia, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_symptoms_ms3_headaches <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_ms3_headaches, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_symptoms_ms4_myalgia <- as.numeric(as.character(factor(famsSRO$fams4_symptoms_ms4_myalgia, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$symptoms <- rowSums(famsSRO[,c(10:16)], na.rm = TRUE)

#emotional well-being SRO
famsSRO$fams4_emotions_ge1_sad <- as.numeric(as.character(factor(famsSRO$fams4_emotions_ge1_sad, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_emotions_ge3_hope <- as.numeric(as.character(factor(famsSRO$fams4_emotions_ge3_hope, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_emotions_ms5_trapped <- as.numeric(as.character(factor(famsSRO$fams4_emotions_ms5_trapped, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_emotions_ms6_depressed <- as.numeric(as.character(factor(famsSRO$fams4_emotions_ms6_depressed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_emotions_ms7_useless <- as.numeric(as.character(factor(famsSRO$fams4_emotions_ms7_useless, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_emotions_ms8_overwhelmed <- as.numeric(as.character(factor(famsSRO$fams4_emotions_ms8_overwhelmed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$emotional <- rowSums(famsSRO[,c(17:23)], na.rm = TRUE)

#general contentment SRO
famsSRO$fams4_contentment_ms9_frustrated <- as.numeric(as.character(factor(famsSRO$fams4_contentment_ms9_frustrated, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$content <- rowSums(famsSRO[,c(24:30)], na.rm = TRUE)

#thinking and fatigue SRO
famsSRO$fams4_fatigue_gp1_energy <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_gp1_energy, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_an2_tired <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_an2_tired, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_an3_starting <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_an3_starting, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_an4_finishing <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_an4_finishing, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_ms10_rest <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_ms10_rest, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_hi9_remembering <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_hi9_remembering, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_hi8_concentrating <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_hi8_concentrating, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_ms11_slow <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_ms11_slow, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_fatigue_ms12_new <- as.numeric(as.character(factor(famsSRO$fams4_fatigue_ms12_new, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$thinking <- rowSums(famsSRO[,c(31:39)], na.rm = TRUE)

#family and social well-being SRO
famsSRO$fams4_social_ms13_understand <- as.numeric(as.character(factor(famsSRO$fams4_social_ms13_understand, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_social_ms14_leftout <- as.numeric(as.character(factor(famsSRO$fams4_social_ms14_leftout, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$family <- rowSums(famsSRO[,c(40:46)], na.rm = TRUE)

#additional concerns SRO
famsSRO$fams4_additional_gp5_sideeffect <- as.numeric(as.character(factor(famsSRO$fams4_additional_gp5_sideeffect, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_gp7_bed <- as.numeric(as.character(factor(famsSRO$fams4_additional_gp7_bed, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_ge4_nervous <- as.numeric(as.character(factor(famsSRO$fams4_additional_ge4_nervous, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_ge6_worse <- as.numeric(as.character(factor(famsSRO$fams4_additional_ge6_worse, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_ms15_heat <- as.numeric(as.character(factor(famsSRO$fams4_additional_ms15_heat, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_bl1_urinecontrol <- as.numeric(as.character(factor(famsSRO$fams4_additional_bl1_urinecontrol, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_bl2_urinefrq <- as.numeric(as.character(factor(famsSRO$fams4_additional_bl2_urinefrq, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_brm2_chills <- as.numeric(as.character(factor(famsSRO$fams4_additional_brm2_chills, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_brm3_fever <- as.numeric(as.character(factor(famsSRO$fams4_additional_brm3_fever, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$fams4_additional_ms16_muscle_spasms <- as.numeric(as.character(factor(famsSRO$fams4_additional_ms16_muscle_spasms, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsSRO$additional <- rowSums(famsSRO[,c(47:60)], na.rm = TRUE)

```

###Final subscores & total
```{r}
#multiply each subgroup total by number of questions in the category
famsSRO$mobility <- famsSRO$mobility*7
famsSRO$symptoms <- famsSRO$symptoms*7
famsSRO$emotional <- famsSRO$emotional*7
famsSRO$content <- famsSRO$content*7
famsSRO$thinking <- famsSRO$thinking*9
famsSRO$family <- famsSRO$family*7
famsSRO$additional <- famsSRO$additional*14

#sum number of scores available
  #change all scores to 1
famsSRO[,c(3:60)] <- ifelse(
    ( 
        (famsSRO[,c(3:60)] >=0)
    ),
     1,  #puts this where conditions are met
     NA  #puts this where conditions are not met
)

  #sum rows to find number of questions answered per subgroup
famsSRO$mobility_count <- rowSums(famsSRO[,c(3:9)], na.rm = TRUE)
famsSRO$symptoms_count <- rowSums(famsSRO[,c(10:16)], na.rm = TRUE)
famsSRO$emotional_count <- rowSums(famsSRO[,c(17:23)], na.rm = TRUE)
famsSRO$content_count <- rowSums(famsSRO[,c(24:30)], na.rm = TRUE)
famsSRO$thinking_count <- rowSums(famsSRO[,c(31:39)], na.rm = TRUE)
famsSRO$family_count <- rowSums(famsSRO[,c(40:46)], na.rm = TRUE)
famsSRO$additional_count <- rowSums(famsSRO[,c(47:60)], na.rm = TRUE)

  #divide subgroup total by # scores available
famsSRO$mobility_final <- famsSRO$mobility/famsSRO$mobility_count
famsSRO$symptoms_final <- famsSRO$symptoms/famsSRO$symptoms_count
famsSRO$emotional_final <- famsSRO$emotional/famsSRO$emotional_count
famsSRO$content_final <- famsSRO$content/famsSRO$content_count
famsSRO$thinking_final <- famsSRO$thinking/famsSRO$thinking_count
famsSRO$family_final <- famsSRO$family/famsSRO$family_count
famsSRO$additional_final <- famsSRO$additional/famsSRO$additional_count

#total
famsSRO$fams_total <- rowSums(famsSRO[,c(75:80)], na.rm = TRUE)

#select final columns
famsSRO <- famsSRO[,c(1,2,75:82)]
famsSRO <- famsSRO %>% filter(fams_total>0)

```

##Update
###Raw subtotals
```{r}
#mobility update
famsUpd$fams4_mobility_gp3_familyneed_b53d71 <- as.numeric(as.character(factor(famsUpd$fams4_mobility_gp3_familyneed_b53d71, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_mobility_an6_walking_c93fd3 <- as.numeric(as.character(factor(famsUpd$fams4_mobility_an6_walking_c93fd3, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_mobility_itu3_social_8c1cdf <- as.numeric(as.character(factor(famsUpd$fams4_mobility_itu3_social_8c1cdf, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_mobility_ms1_public_750840 <- as.numeric(as.character(factor(famsUpd$fams4_mobility_ms1_public_750840, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_mobility_ms2_plan_73bf20 <- as.numeric(as.character(factor(famsUpd$fams4_mobility_ms2_plan_73bf20, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$mobility <- rowSums(famsUpd[,c(3:9)], na.rm = TRUE)

#symptoms update
famsUpd$fams4_symptoms_gp2_nausea_5bdf98 <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_gp2_nausea_5bdf98, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_symptoms_gp4_pain_607f51 <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_gp4_pain_607f51, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_symptoms_gp6_ill_7e2187 <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_gp6_ill_7e2187, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_symptoms_hi12_weak_6c9f4a <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_hi12_weak_6c9f4a, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_symptoms_brm1_arthralgia_57b850 <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_brm1_arthralgia_57b850, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_symptoms_ms3_headaches_80d03d <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_ms3_headaches_80d03d, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_symptoms_ms4_myalgia_da56e1 <- as.numeric(as.character(factor(famsUpd$fams4_symptoms_ms4_myalgia_da56e1, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$symptoms <- rowSums(famsUpd[,c(10:16)], na.rm = TRUE)

#emotional well-being update
famsUpd$fams4_emotions_ge1_sad_6a79d1 <- as.numeric(as.character(factor(famsUpd$fams4_emotions_ge1_sad_6a79d1, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_emotions_ge3_hope_0ed8e5 <- as.numeric(as.character(factor(famsUpd$fams4_emotions_ge3_hope_0ed8e5, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_emotions_ms5_trapped_282095 <- as.numeric(as.character(factor(famsUpd$fams4_emotions_ms5_trapped_282095, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_emotions_ms6_depressed_2c96c3 <- as.numeric(as.character(factor(famsUpd$fams4_emotions_ms6_depressed_2c96c3, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_emotions_ms7_useless_400e06 <- as.numeric(as.character(factor(famsUpd$fams4_emotions_ms7_useless_400e06, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_emotions_ms8_overwhelmed_a7b68e <- as.numeric(as.character(factor(famsUpd$fams4_emotions_ms8_overwhelmed_a7b68e, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$emotional <- rowSums(famsUpd[,c(17:23)], na.rm = TRUE)

#general contentment update
famsUpd$fams4_contentment_ms9_frustrated_676f92 <- as.numeric(as.character(factor(famsUpd$fams4_contentment_ms9_frustrated_676f92, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$content <- rowSums(famsUpd[,c(24:30)], na.rm = TRUE)

#thinking and fatigue update
famsUpd$fams4_fatigue_gp1_energy_454f09 <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_gp1_energy_454f09, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_an2_tired_c70445 <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_an2_tired_c70445, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_an3_starting_d42a25 <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_an3_starting_d42a25, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_an4_finishing_e281ac <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_an4_finishing_e281ac, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_ms10_rest_f185a9 <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_ms10_rest_f185a9, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_hi9_remembering_ee08c8 <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_hi9_remembering_ee08c8, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_hi8_concentrating_19e0e7 <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_hi8_concentrating_19e0e7, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_ms11_slow_f29f1e <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_ms11_slow_f29f1e, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_fatigue_ms12_new_a03d8b <- as.numeric(as.character(factor(famsUpd$fams4_fatigue_ms12_new_a03d8b, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$thinking <- rowSums(famsUpd[,c(31:39)], na.rm = TRUE)

#family and social well-being update
famsUpd$fams4_social_ms13_understand_80d3bf <- as.numeric(as.character(factor(famsUpd$fams4_social_ms13_understand_80d3bf, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_social_ms14_leftout_300121 <- as.numeric(as.character(factor(famsUpd$fams4_social_ms14_leftout_300121, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$family <- rowSums(famsUpd[,c(40:46)], na.rm = TRUE)

#additional concerns update
famsUpd$fams4_additional_gp5_sideeffect_df5964 <- as.numeric(as.character(factor(famsUpd$fams4_additional_gp5_sideeffect_df5964, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_gp7_bed_b10fe5 <- as.numeric(as.character(factor(famsUpd$fams4_additional_gp7_bed_b10fe5, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_ge4_nervous_19ad68 <- as.numeric(as.character(factor(famsUpd$fams4_additional_ge4_nervous_19ad68, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_ge6_worse_99bed6 <- as.numeric(as.character(factor(famsUpd$fams4_additional_ge6_worse_99bed6, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_ms15_heat_d91bde <- as.numeric(as.character(factor(famsUpd$fams4_additional_ms15_heat_d91bde, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_bl1_urinecontrol_d3cf02 <- as.numeric(as.character(factor(famsUpd$fams4_additional_bl1_urinecontrol_d3cf02, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_bl2_urinefrq_5a737f <- as.numeric(as.character(factor(famsUpd$fams4_additional_bl2_urinefrq_5a737f, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_brm2_chills_360470 <- as.numeric(as.character(factor(famsUpd$fams4_additional_brm2_chills_360470, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_brm3_fever_e4df50 <- as.numeric(as.character(factor(famsUpd$fams4_additional_brm3_fever_e4df50, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$fams4_additional_ms16_muscle_spasms_b403f3 <- as.numeric(as.character(factor(famsUpd$fams4_additional_ms16_muscle_spasms_b403f3, levels = c(0,1,2,3,4), labels = c(4,3,2,1,0))))
famsUpd$additional <- rowSums(famsUpd[,c(47:60)], na.rm = TRUE)

```

###Final subscores & total
```{r}
#multiply each subgroup total by number of questions in the category
famsUpd$mobility <- famsUpd$mobility*7
famsUpd$symptoms <- famsUpd$symptoms*7
famsUpd$emotional <- famsUpd$emotional*7
famsUpd$content <- famsUpd$content*7
famsUpd$thinking <- famsUpd$thinking*9
famsUpd$family <- famsUpd$family*7
famsUpd$additional <- famsUpd$additional*14

#sum number of scores available
  #change all scores to 1
famsUpd[,c(3:60)] <- ifelse(
    ( 
        (famsUpd[,c(3:60)] >=0)
    ),
     1,  #puts this where conditions are met
     NA  #puts this where conditions are not met
)

  #sum rows to find number of questions answered per subgroup
famsUpd$mobility_count <- rowSums(famsUpd[,c(3:9)], na.rm = TRUE)
famsUpd$symptoms_count <- rowSums(famsUpd[,c(10:16)], na.rm = TRUE)
famsUpd$emotional_count <- rowSums(famsUpd[,c(17:23)], na.rm = TRUE)
famsUpd$content_count <- rowSums(famsUpd[,c(24:30)], na.rm = TRUE)
famsUpd$thinking_count <- rowSums(famsUpd[,c(31:39)], na.rm = TRUE)
famsUpd$family_count <- rowSums(famsUpd[,c(40:46)], na.rm = TRUE)
famsUpd$additional_count <- rowSums(famsUpd[,c(47:60)], na.rm = TRUE)

  #divide subgroup total by # scores available
famsUpd$mobility_final <- famsUpd$mobility/famsUpd$mobility_count
famsUpd$symptoms_final <- famsUpd$symptoms/famsUpd$symptoms_count
famsUpd$emotional_final <- famsUpd$emotional/famsUpd$emotional_count
famsUpd$content_final <- famsUpd$content/famsUpd$content_count
famsUpd$thinking_final <- famsUpd$thinking/famsUpd$thinking_count
famsUpd$family_final <- famsUpd$family/famsUpd$family_count
famsUpd$additional_final <- famsUpd$additional/famsUpd$additional_count

#total
famsUpd$fams_total <- rowSums(famsUpd[,c(75:80)], na.rm = TRUE)

#select final columns
famsUpd <- famsUpd[,c(1,2,75:82)]
famsUpd <- famsUpd %>% filter(fams_total>0)

```


#Combine all
```{r}
fams_all <- rbind(famsLeg, famsSRO, famsUpd)
fams_all <- fams_all[order(fams_all$id_participant, fams_all$timestamp), ]
fams_all$timestamp <- as.Date(fams_all$timestamp)
fams_all[,c(3:10)] <- round(fams_all[,c(3:10)], digits = 0)

#export- all fams scores for all participants
write.csv(fams_all, "fams.csv")

```

#Basic stats
```{r}
#2349 scores

mean(fams_all$fams_total)  #mean of all scores is 118
sd(fams_all$fams_total)  #sd is 34.42
range(fams_all$fams_total)  #range is 7 - 176
median(fams_all$fams_total)  #median is 119

sum(table(unique(fams_all$id_participant)))  #1103 participants w/ at least 1 score

test <- data.frame(table(fams_all$id_participant))
test <- test %>% filter(Freq>0)
mean(test$Freq) #average 2 scores per participant
test2 <- data.frame(table(test$Freq))
  #586 participants with 1 score
  #255 participants with 2 scores
  #143 participants with 3 scores
  #106 participants with 4 scores
  #80 participants with 5 scores

#finds info for first score per participant
first <- fams_all %>%
  group_by(id_participant) %>%
  mutate(diff = lag(timestamp, default = first(timestamp), order_by = timestamp) - timestamp)
first <- first %>% filter(diff==0)
  #first scores for 967 participants (not 1170 because some scores don't have timestamps- that disqualifies all scores for that participant b/c we can't tell which score is first)
mean(first$fams_total)  #mean is 119
sd(first$fams_total)  #sd is 34.72
range(first$fams_total)  #range is 20 - 176
median(first$fams_total)  #median is 120


```

#Visualization
```{r}
# hist(fams_all$mobility_final)
# hist(fams_all$symptoms_final)
# hist(fams_all$emotional_final)
# hist(fams_all$content_final)
# hist(fams_all$thinking_final)
# hist(fams_all$family_final)
# hist(fams_all$additional_final)
hist(fams_all$fams_total)

ggplot(data=fams_all, aes(fams_total)) +
  geom_bar() + 
  theme_minimal() +
  labs(title = "FAMS Scores") + theme(plot.title = element_text(hjust = 0.5)) + xlab("FAMS Score") + ylab("Number of Responses")

vistest <- fams_all[order(fams_all$fams_total, fams_all$id_participant), ]
vistest$responseID <- 1:nrow(vistest)

ggplot(data = vistest, aes(x=timestamp, y = fams_total)) +
  geom_bar(stat = "identity") + 
  theme_minimal() +
  labs(title = "FAMS Breakdown") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Survey Response Number") + ylab("FAMS Score")

vistest <- vistest %>% pivot_longer(., cols = c("mobility_final", "symptoms_final", "emotional_final", "content_final", "thinking_final", "family_final"))
names(vistest)[6] <- 'score_name'
names(vistest)[7] <- 'score_value'

ggplot(data = vistest, aes(x=responseID, y = score_value, fill=score_name)) +
  geom_bar(stat = "identity") + 
  theme_minimal() +
  labs(title = "FAMS Breakdown") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Survey Response Number") + ylab("FAMS Score")

vistest2 <- vistest %>% filter(fams_total ==150) #use this as an example to isolate a few participants
ggplot(data = vistest2, aes(x=responseID, y = score_value, fill=score_name)) +
  geom_bar(stat = "identity") + 
  theme_minimal() +
  labs(title = "FAMS Breakdown") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Survey Response Number") + ylab("FAMS Score")

#earliest score
fams_all$timestamp  <- as.Date(fams_all$timestamp)
fams_earliest = aggregate(fams_all$timestamp,by=list(fams_all$id_participant),min)
names(fams_earliest)[1] <- 'id_participant'
names(fams_earliest)[2] <- 'timestamp'
fams_earliest <- merge(fams_earliest, fams_all, by.x=c("id_participant", "timestamp"), by.y=c("id_participant", "timestamp"), all.x = TRUE)

ggplot(data=fams_earliest, aes(fams_total)) +
  geom_bar() + 
  geom_vline(aes(xintercept=mean(fams_total, na.rm = TRUE)), color="#E74C3C", linetype="dashed", size=.5) +
  theme_linedraw() + 
  theme(plot.title = element_text(hjust = 0.5)) + xlab("FAMS Score") + ylab("Number of Participants") + 
  theme(axis.title.x = element_text(margin = margin(t = 15)), axis.title.y = element_text(margin = margin(r=15))) 



```



