---
title: "SSS Scoring"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(data.table)
library(tableone)
library(stringr)
library(tidyr)
library(table1)
library(plyr)
library(dplyr)
library(knitr)

# This code finds all sss scores for all PROMOTE participants
  #SSS: Longitudinal SRO & Update, Legacy SRO

#CHANGE FILE PATHS

```

#Import Files
```{r}
#setwd("your_working_directory")

longitudinal1 <- read.csv("long1.csv") #PROMOTE longitudinal project 1
longitudinal2 <- read.csv("long2.csv") #PROMOTE longitudinal project 2
longitudinal <- rbind(longitudinal1, longitudinal2)
longitudinal <- longitudinal %>% filter(!str_detect(id_participant_l, "_x"))

legacy <- read.csv("PQ_SRO_Legacy.csv") #Export of the whole PQ/SRO Legacy project
missingID <- read.csv("MissingIdentifiers.csv") #Missing ID reference file
legacy <- (merge(missingID, legacy, by = 'record_id',  all.y = TRUE))
paste_noNA <- function(x,sep=", ") {
gsub(", " ,sep, toString(x[!is.na(x) & x!="" & x!="NA"] ) ) }
sep=", "
legacy$id_participant<- apply( legacy[ , c(2:3) ] , 1 , paste_noNA , sep=sep)


```

#Legacy
```{r}
#SRO
sssLeg <- legacy[,c("id_participant", "promote_self_reported_outcomes_timestamp", "sss_1_partner", "sss_2_amount", "sss_3_variety", "sss_4_general", "sss_5_partner")]
names(sssLeg)[2] <- 'sss_date'
names(sssLeg)[3] <- 'sss_partner'

```

#Longitudinal
```{r}
#SRO & Update
sssLong <- longitudinal[,c("id_participant_l", "promote_self_reported_outcomes_timestamp", "sss_1_partner", "sss_2_amount", "sss_3_variety", "sss_4_general", "sss_5_partner",
                            "update_questionnaire_timestamp", "sss_1_partner", "sss_2_amount_0c0ed8", "sss_3_variety_ed8c0a", "sss_4_general_064719", "sss_5_partner_6707c1")]

sssLongDate <- sssLong %>% gather(dateNumber, sss_date, 2,8)
sssLongQ1 <- sssLong %>% gather(question1, sss_partner, 3,9)
sssLongScore1 <- sssLong %>% gather(scoreNumber1, sss_1_amount, 4,10)
sssLongScore2 <- sssLong %>% gather(scoreNumber2, sss_2_variety, 5,11)
sssLongScore3 <- sssLong %>% gather(scoreNumber3, sss_3_general, 6,12)
sssLongScore4 <- sssLong %>% gather(scoreNumber4, sss_4_partner, 7,13)

sssLong <- cbind(sssLongDate, sssLongQ1, sssLongScore1, sssLongScore2, sssLongScore3, sssLongScore4)
sssLong <- sssLong[,c("id_participant_l", "sss_date", "sss_partner", "sss_2_amount", "sss_3_variety", "sss_4_general", "sss_5_partner")]
names(sssLong)[1] <- 'id_participant'

```

#Combine and score
```{r}
#Combine
sss_All <- rbind(sssLeg, sssLong)

#add all items
sss_All$sss_total <- rowSums(sss_All[,c(4:7)])
  #remove responses where the partner question is not answered
sss_All <- sss_All %>% filter(!is.na(sss_partner))
  #remove responses where the partner question is answered, but there are NAs in the responses
sss_All <- sss_All %>% filter((!(sss_partner==1 & is.na(sss_total))))

#export
write.csv(sss_All, "sss.csv")

```

#Basic stats
```{r}
#number of responses without a primary partner
sss_All %>% filter(sss_partner==0) #358

#ONLY FOR SCORES WITH PRIMARY PARTNER
sss_partner <- sss_All %>% filter(sss_partner==1)

#1305 scores
mean(sss_partner$sss_total)  #mean of all scores is 11.7
sd(sss_partner$sss_total)  #sd is 6.8
range(sss_partner$sss_total)  #range is 4-24
median(sss_partner$sss_total)  #median is 10

sum(table(unique(sss_partner$id_participant)))  #806 participants w/ at least 1 score

test <- data.frame(table(sss_partner$id_participant))
test <- test %>% filter(Freq>0)
mean(test$Freq) #average 1.6 scores per participant
test2 <- data.frame(table(test$Freq))
  #310 participants with 1 score
  #6493 participants with 2 scores
  #3 participants with 3 scores

#finds info for the first score per participant
sss_partner$sss_date <- as.Date(sss_partner$sss_date)
first <- sss_partner %>%
  group_by(id_participant) %>%
  mutate(diff = lag(sss_date, default = first(sss_date), order_by = sss_date) - sss_date)
first <- first %>% filter(diff==0)
  #first scores for 771 participants
mean(first$sss_total)  #mean is 11.7
sd(first$sss_total)  #sd is 6.8
range(first$sss_total)  #range is 4-24
median(first$sss_total)  #median is 10

```

#Visualization
```{r}
hist(sss_partner$sss_total)

```


